### ISSUE TITLE
Comparison to `lattices`

### ISSUE THREAD

**Issue by phadej** [mtesseract/haskell-partial-order#4]
I see `partial-order` has some additional combinators, not present in http://hackage.haskell.org/package/lattices, but is there any other reasons to prefer one over another?

**Comment by mtesseract** [comment]
Hi,

I'm not familiar with the `lattices` package, but it seems to me that they are rather different. `partial-order` really focuses on that: defining a type class for partial orders & providing instances for several types. Since partial orders induce a notion of equality, my package also provides some convenience functions like `elem` or `nub`.

It doesn't introduce the notion of lattices.

Also, it provides instances and functions for e.g. testing for the subset-relation of lists out of the box:

    Prelude> import qualified Data.PartialOrd as PO
    Prelude PO> [3,1] PO.<= [1..10]
    True
    Prelude PO> 

Does this answer your question?

**Comment by phadej** [comment]
Partially,

`lattices` has [`Algebra.PartialOrd`](http://hackage.haskell.org/package/lattices-1.6.0/docs/Algebra-PartialOrd.html) too. And there is instances for subset partial order for `Set`.

There isn't a partial order for lists, but if added it probably be subrange relation (i.e. `isInfixOf`)

**Comment by mtesseract** [comment]
Ok, as I understand it we can summarize: The packages have some overlap, but don't provide equivalent functionality. What do you think, shall we close the issue?

**Comment by andreasabel** [comment]
> `lattices` has [`Algebra.PartialOrd`](http://hackage.haskell.org/package/lattices-1.6.0/docs/Algebra-PartialOrd.html) too. And there is instances for subset partial order for `Set`.

Some comparison between the interfaces in `lattices` and `partial-order` is here: 
- https://github.com/haskellari/lattices/issues/117

(Unfortunately, neither interface fits my needs: _connectedness_ of nodes in a DAG is a partial order, but it is relative to a context (the DAG), a nodes in a particular DAG do not make a good Haskell type.)
